firstname_field_loc = "#firstname"
lastname_field_loc = "#lastname"
email_field_loc = "#email_address"
password_field_loc = "#password"
password_confirmation_field_loc = "#password-confirmation"
buttom_create_acc_loc = "//button[@title='Create an Account']"
error_locator_loc = "#email_address-error"
header_loc = "h1"
confirm_password_locator = "#password-confirmation-error"
# error locators
first_name_error_locator = "#firstname-error"
last_name_error_locator = "#lastname-error"
email_error_locator = "#email_address-error"
password_error_locator = "#password-error"
confirm_password_error_locator = "#password-confirmation-error"
